export type ExtensionParameters = {
  GOOGLE_SPREADSHEET_ID: string;
  GOOGLE_SPREADSHEET_SHEET_ID: string;
  ALLOWED_FIELDS?: string;
  APP_CHECK: "yes" | "no";
  GOOGLE_API_CREDENTIALS_CLIENT_EMAIL?: string;
  GOOGLE_API_CREDENTIALS_PRIVATE_KEY?: string;
  EMPTY_CELL: string;
};

const {
  GOOGLE_SPREADSHEET_ID,
  GOOGLE_SPREADSHEET_SHEET_ID,
  ALLOWED_FIELDS,
  APP_CHECK,
  GOOGLE_API_CREDENTIALS_CLIENT_EMAIL,
  GOOGLE_API_CREDENTIALS_PRIVATE_KEY,
  EMPTY_CELL = "",
} = process.env as ExtensionParameters;

export const extensionParameters: ExtensionParameters = {
  GOOGLE_SPREADSHEET_ID,
  GOOGLE_SPREADSHEET_SHEET_ID,
  ALLOWED_FIELDS,
  APP_CHECK,
  GOOGLE_API_CREDENTIALS_CLIENT_EMAIL,
  GOOGLE_API_CREDENTIALS_PRIVATE_KEY,
  EMPTY_CELL,
};
